### ISSUE TITLE
Widgets on other pages fail to show

### ISSUE THREAD

**Issue by NattyE** [att/rcloud.rcap#122] opened 2016-08-05 11:17 UTC
This is due to the height sizing of the iframe being set to 0 when plots are refreshed and you are on a different page - the widgets are in fact there and are rendering they just don't show due to their height.

**Comment by shaneporter** [comment] 2016-08-05 19:59
I'd have to have a look at what's actually rendering and when, but I suspect everything is rendering at once. This is both inefficient and error prone. There's already an event that is fired when a page changes. The handler for this will need to be changed so that not only does it show the controls, but they are updated.

**Comment by gaborcsardi** [comment] 2016-08-10 13:07
Duplicate of #96 ?

**Comment by gaborcsardi** [comment] 2016-08-10 13:25
It is.

**Closed by gaborcsardi** 2016-08-10 13:25 UTC
Labels: bug
